import {
  FileText,
  User,
  Hospital,
  Building2,
  Pill,
  Stethoscope,
  CreditCard,
  ShieldCheck,
  Gavel,
  HeartHandshake,
  Zap,
  ClipboardList,
  MessageSquare,
  File,
  Printer,
  Send,
  CheckCircle2,
  XCircle,
  Clock,
  AlertTriangle,
  Hourglass,
  Archive,
  Search,
  MoreHorizontal,
  Pin,
  Paperclip,
  Upload,
  Download,
  Pencil,
  Settings,
  LifeBuoy,
  BarChart3,
  Sparkles,
} from "lucide-react";

/**
 * Concept → icon vocabulary for the UI v2 design system. Use this instead of
 * importing lucide components ad hoc, so the same concept always renders the
 * same glyph across clinic and admin surfaces. Pair with `Icon` from
 * `@/components/ui/icon` for consistent size/stroke.
 */
export const ICONS = {
  referral: FileText,
  patient: User,
  clinic: Hospital,
  pharmacy: Building2,
  drug: Pill,
  prescriber: Stethoscope,
  insurance: CreditCard,
  priorAuth: ShieldCheck,
  appeal: Gavel,
  enrollment: HeartHandshake,
  bridge: Zap,
  task: ClipboardList,
  note: MessageSquare,
  document: File,
  fax: Printer,
  sent: Send,
  approve: CheckCircle2,
  reject: XCircle,
  due: Clock,
  overdue: AlertTriangle,
  waiting: Hourglass,
  archive: Archive,
  search: Search,
  more: MoreHorizontal,
  pin: Pin,
  attach: Paperclip,
  upload: Upload,
  download: Download,
  edit: Pencil,
  settings: Settings,
  support: LifeBuoy,
  insights: BarChart3,
  aiQuality: Sparkles,
} as const;

export type IconConcept = keyof typeof ICONS;
